version: "3.8"
services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    volumes:
      - ollama_data:/root/.ollama
      - ./docker/ollama.entrypoint.sh:/entrypoint.sh
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_USE_GPU=1
    restart: unless-stopped
    entrypoint: ["/bin/sh", "/entrypoint.sh"]
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

  quizcraft-api:
    build:
      context: .
      dockerfile: docker/fastapi.dockerfile
    container_name: mcq-backend
    depends_on:
      - ollama
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_URL=http://ollama:11434
      - OLLAMA_MODEL=llama3.2
    restart: on-failure
    volumes:
      - ./uploads:/uploads
      - ./src:/app/src
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

volumes:
  ollama_data:
