from .env import UPLOAD_FOLDER, OLLAMA_URL, OLLAMA_MODEL, GENERATIVE_PROVIDER, GEMINI_MODEL, GEMINI_API_KEY
from .prompts import MCQ_GEN_PROMPT, CLEANER_PROMPT, VALIDATE_PROMPT

__all__ = ["OLLAMA_MODEL", "UPLOAD_FOLDER", "OLLAMA_URL", "GENERATIVE_PROVIDER", "GEMINI_MODEL", "MCQ_GEN_PROMPT", "CLEANER_PROMPT", "VALIDATE_PROMPT", "GEMINI_API_KEY"]
