from .const import UPLOAD_FOLDER, OLLAMA_URL, OLLAMA_MODEL
from .prompts import MCQ_GEN_PROMPT, CLEANER_PROMPT, CHUNKING_PROMPT

__all__ = ["OLLAMA_MODEL", "UPLOAD_FOLDER", "OLLAMA_URL", "MCQ_GEN_PROMPT", "CLEANER_PROMPT", "CHUNKING_PROMPT"]
